cker file for EP stage python container
FROM python:3.6

# Upgrade System:
RUN apt-get update\
	&& apt-get -y upgrade \
	&& apt-get -y autoremove

# Download and install dependencies
RUN apt-get install -qq \
	build-essential \
	libssl-dev \
	libxrender-dev \
	wget \
	git \
	wkhtmltopdf

#Our Docker commands:
RUN mkdir -p {{ ep19_code_deploy_path_in_docker }}
WORKDIR {{ ep19_code_deploy_path_in_docker }}

RUN git clone \
	-b {{ ep19_deploy_branch }} \
	{{ ep19_repository_url }} \
	.

RUN make install
RUN pip install greenlet  # Required for both
RUN pip install eventlet  # For eventlet workers
RUN pip install gevent	  # For gevent workers
