
#- name: Get latest source code
#  git: >
#    repo={{ ep19_repository_url }}
#    dest={{ ep19_code_deploy_path }}
#    version={{ ep19_deploy_branch }}
#    accept_hostkey=yes


- name: Make sure that deploy directory exists
  file: >
    path={{ ep19_docker_deploy_path }} state=directory
    owner=ubuntu group=ubuntu mode=0755

- name: Set up Dockerfile
  template:
      src: Dockerfile.j2
      dest: "{{ ep19_docker_deploy_path }}/Dockerfile"
      owner: ubuntu
      group: ubuntu
      mode: 0644

- name: Set up docker-compose
  template:
      src: docker-compose.yml.j2
      dest: "{{ ep19_docker_deploy_path }}/docker-compose.yaml"
      owner: ubuntu
      group: ubuntu
      mode: 0644

#- name: Register with nginx sites-available/enabled
