---

- name: Install required packages
  become: yes
  become_method: sudo
  apt:
      update_cache: yes
      name: "{{ packages }}"
  vars:
      packages:
          - python3
          - nginx
          - docker
          - docker-compose
